"""Section F: API endpoint tests.

Uses FastAPI TestClient — no server needed.  Requires the precomputed
results file to exist (generated by test_04_precompute or precompute.py).
"""

import os
import sys
import json
import pytest
from fastapi.testclient import TestClient

BACKEND_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, BACKEND_DIR)

from main import app

client = TestClient(app)

EXPECTED_CASE_IDS = {"case_pass", "case_bad_search", "case_bad_tool", "case_bad_generation", "case_ambiguous"}


def test_get_cases_returns_200():
    resp = client.get("/api/cases")
    assert resp.status_code == 200
    data = resp.json()
    assert isinstance(data, list)
    assert len(data) == 5


def test_get_cases_has_required_fields():
    resp = client.get("/api/cases")
    data = resp.json()
    for entry in data:
        assert "id" in entry
        assert "question" in entry
        assert "is_correct" in entry
    ids = {e["id"] for e in data}
    assert ids == EXPECTED_CASE_IDS


def test_get_trace_bad_search():
    resp = client.get("/api/cases/case_bad_search/trace")
    assert resp.status_code == 200
    data = resp.json()
    assert "case_id" in data
    assert "question" in data
    assert "steps" in data
    assert "final_answer" in data
    assert "is_correct" in data
    assert data["is_correct"] is False
    for step in ["search", "tool", "answer"]:
        assert step in data["steps"], f"Missing step: {step}"
        assert "input" in data["steps"][step]
        assert "output" in data["steps"][step]


def test_get_trace_pass_returns_200():
    resp = client.get("/api/cases/case_pass/trace")
    assert resp.status_code == 200
    assert resp.json()["is_correct"] is True


def test_get_trace_nonexistent_returns_404():
    resp = client.get("/api/cases/nonexistent_case/trace")
    assert resp.status_code == 404
    body = resp.json()
    assert "detail" in body, f"Expected clean error body, got: {body}"
    # Must NOT be a 500 or raw traceback
    assert resp.status_code == 404


def test_get_diagnosis_bad_search():
    resp = client.get("/api/cases/case_bad_search/diagnosis")
    assert resp.status_code == 200
    data = resp.json()
    assert data["root_causes"] == ["search"]
    assert "blame_scores" in data
    assert "explanation" in data
    assert data["original_correct"] is False


def test_get_diagnosis_pass():
    resp = client.get("/api/cases/case_pass/diagnosis")
    assert resp.status_code == 200
    data = resp.json()
    assert data["root_causes"] == []
    assert data["original_correct"] is True


def test_get_diagnosis_nonexistent_returns_404():
    resp = client.get("/api/cases/nonexistent_case/diagnosis")
    assert resp.status_code == 404
    assert "detail" in resp.json()


def test_post_diagnose_live_bad_search():
    resp = client.post("/api/cases/case_bad_search/diagnose-live")
    assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"
    data = resp.json()
    assert data["root_causes"] == ["search"]
    assert "blame_scores" in data
    assert "explanation" in data
    assert data["original_correct"] is False
    # used_fallback should be absent or False when API key is valid
    if "used_fallback" in data:
        assert data["used_fallback"] is False


def test_post_diagnose_live_pass():
    resp = client.post("/api/cases/case_pass/diagnose-live")
    assert resp.status_code == 200
    data = resp.json()
    assert data["original_correct"] is True
    assert data["root_causes"] == []


def test_post_diagnose_live_nonexistent():
    resp = client.post("/api/cases/nonexistent_case/diagnose-live")
    assert resp.status_code == 404


def test_cors_preflight():
    """OPTIONS preflight from localhost:5173 should return correct CORS header."""
    resp = client.options(
        "/api/cases",
        headers={
            "Origin": "http://localhost:5173",
            "Access-Control-Request-Method": "GET",
        },
    )
    assert resp.status_code == 200
    assert resp.headers.get("access-control-allow-origin") == "http://localhost:5173"


def test_cors_preflight_trace():
    resp = client.options(
        "/api/cases/case_bad_search/trace",
        headers={
            "Origin": "http://localhost:5173",
            "Access-Control-Request-Method": "GET",
        },
    )
    assert resp.status_code == 200
    assert resp.headers.get("access-control-allow-origin") == "http://localhost:5173"


def test_cors_preflight_diagnose_live():
    resp = client.options(
        "/api/cases/case_bad_search/diagnose-live",
        headers={
            "Origin": "http://localhost:5173",
            "Access-Control-Request-Method": "POST",
        },
    )
    assert resp.status_code == 200
    assert resp.headers.get("access-control-allow-origin") == "http://localhost:5173"


def test_trace_schema_matches_spec():
    """Trace response must match the schema from the build spec."""
    resp = client.get("/api/cases/case_bad_search/trace")
    data = resp.json()
    # Schema: { case_id, question, steps: { search, tool, answer }, final_answer, is_correct }
    assert isinstance(data["case_id"], str)
    assert isinstance(data["question"], str)
    assert isinstance(data["steps"], dict)
    assert set(data["steps"].keys()) == {"search", "tool", "answer"}
    assert isinstance(data["final_answer"], str)
    assert isinstance(data["is_correct"], bool)
    for step in ["search", "tool", "answer"]:
        assert "input" in data["steps"][step]
        assert "output" in data["steps"][step]
